#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

###########
# Aliases #
###########

# Color ls
alias ls='ls -GlahF'

# Display as a list
alias ll='pwd; ls -1ah'

# Display the insides of a particular directory
alias lv='pwd; ls -R'

alias grep="grep --color=always"

# GitTips help:
# https://git.wiki.kernel.org/index.php/GitTips

